language: node_js
if: branch =~ /(^release\/.+)|master/
node_js:
    - '8'
install:
    - npm install
script:
    - npm run build
after_script: 
  if [ branch = master ]; then
    tar -cvf dist.tar ./dist
    echo 'master building'
  else
    echo 'release building'
  fi
notifications:
    webhooks:
        - http://another-domain.com/notifications
