language: node_js
if: branch =~ /(^release\/.+)|master/
node_js:
    - '8'
install:
    - npm install
script:
  - 'if [ $TRAVIS_BRANCH = "master"]; then
      npm run build;
      echo "master";
    else 
      npm run build;
      echo "release";
    fi'
after_script:
  - 'if [ $TRAVIS_BRANCH = "master"]; then
      tar -cvf "dist.tar" ./dist
      node .travis.js $TRAVIS_BRANCH
      curl -v "http://pic.to8to.com/case/1809/07/20180907_3572c3f6a5766fff2165ek62jbqn4cg0.jpg?b=$TRAVIS_BRANCH"
      echo "$TRAVIS_BRANCH build";
    else 
      tar -cvf "dist.tar" ./dist
      node .travis.js $TRAVIS_BRANCH
      curl -v "http://pic.to8to.com/case/1809/07/20180907_3572c3f6a5766fff2165ek62jbqn4cg0.jpg?b=$TRAVIS_BRANCH"
      echo "$TRAVIS_BRANCH build";
    fi'

notifications:
    webhooks:
        - http://another-domain.com/notifications
