language: node_js
if: branch =~ /(^release\/.+)|master/
node_js:
    - '8'
install:
    - npm install
script:
  if: branch = master
      - npm run build;
      - echo 'master run build'
  if: branch =~ /^release\/.+/
      - echo 'release run build'
after_script: 
  if: branch = master
      - tar -cvf dist.tar ./dist
      - echo 'master built'
  if: branch =~ /^release\/.+/
      - echo 'release built'
notifications:
    webhooks:
        - http://another-domain.com/notifications
