language: node_js
if: branch =~ /(^release\/.+)|master/
node_js:
    - '8'
install:
    - npm install
script:
  - if [[ branch = master ]]; then npm run build; echo 'master run build'; else echo 'release run build'; fi
after_script: 
  - if [[ branch = master ]]; then tar -cvf dist.tar ./dist; echo 'master built'; else echo 'release built'; fi
notifications:
    webhooks:
        - http://another-domain.com/notifications
