language: node_js
if: branch =~ /(^release\/.+)|master/
node_js:
    - '8'
install:
    - npm install
script:
  if: branch = master
    - npm run build;
    - echo "master"
  if: branch =~ /^release\/.+/
    - npm run build;
    - echo "release"
notifications:
    webhooks:
        - http://another-domain.com/notifications
